"""add language to posts

Revision ID: 331557a4ff13
Revises: 466c25101706
Create Date: 2021-05-31 00:43:11.278879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331557a4ff13'
down_revision = '466c25101706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
